import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api } from "../services/api";
import { uploadImage } from "../services/upload";
import { toast } from "sonner";
type Fee = { id: number; booking_id: number; restaurant_id: number; amount: number; settled_amount: number; deducted_amount: number; due_at: string; proof_url?: string };
export default function BookingFees({ admin = false }: { admin?: boolean }) {
  const qc = useQueryClient(); const [uploading, setUploading] = useState(false);
  const fees = useQuery<Fee[]>({ queryKey: ["booking-fees"], queryFn: () => api.get("/v1/booking-fees").then(r => r.data) });
  const paid = useMutation({ mutationFn: ({ id, proof }: { id: number; proof: string }) => api.put(`/v1/booking-fees/${id}/paid`, { proof_url: proof }), onSuccess: () => { toast.success("Đã ghi nhận thanh toán phí"); void qc.invalidateQueries({ queryKey: ["booking-fees"] }); }, onError: () => toast.error("Không ghi nhận được thanh toán. Vui lòng tải lại dữ liệu.") });
  return <section className="space-y-3 rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Phí dịch vụ đặt bàn</h2><p className="text-sm text-gray-500">Tính trên từng đơn hoàn thành; đến hạn đầu tháng kế tiếp sẽ khấu trừ số dư cọc khả dụng. Phần còn thiếu được nhắc hàng tháng.</p>{fees.isLoading ? <p>Đang tải…</p> : fees.isError ? <p>Không tải được phí dịch vụ.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Đơn / Nhà hàng</th><th>Hạn phí</th><th>Phí</th><th>Còn nợ</th><th>Khấu trừ cọc</th>{admin && <th>Xác nhận tiền đã nhận</th>}</tr></thead><tbody>{fees.data?.map(f => <tr key={f.id} className="border-t"><td className="py-3">#{f.booking_id} / #{f.restaurant_id}</td><td>{new Date(f.due_at).toLocaleDateString("vi-VN", { timeZone: "Asia/Ho_Chi_Minh" })}</td><td>{f.amount.toLocaleString()}đ</td><td>{(f.amount-f.settled_amount).toLocaleString()}đ</td><td>{f.deducted_amount.toLocaleString()}đ</td>{admin && <td>{f.settled_amount < f.amount ? <label className="text-blue-700">Tải minh chứng đã nhận đủ số còn nợ<input type="file" accept="image/*" disabled={uploading || paid.isPending} onChange={async e => { const file=e.target.files?.[0]; if (!file) return; setUploading(true); try { const proof=await uploadImage(file); paid.mutate({ id:f.id, proof }); } catch { toast.error("Không tải được ảnh"); } finally { setUploading(false); } }}/></label> : "Đã thanh toán"}</td>}</tr>)}</tbody></table>{!fees.data?.length && <p className="py-4">Chưa phát sinh phí.</p>}</div>}</section>;
}
