import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { api } from "../services/api";
import { useAuth } from "../hooks/useAuth";
import { useLocation } from "../hooks/useLocation";
import { RESTAURANT_CATEGORIES } from "../utils/category";
import type { RestaurantCard } from "../types/restaurant";

type Preference = { categories: string[]; suitable_for: string[]; service_types: string[]; price_level: number | null; city: string | null };
type Recommended = RestaurantCard & { match_reasons: string[] };
const occasions = [["gia-dinh", "Gia đình"], ["hen-ho", "Hẹn hò"], ["ban-be", "Bạn bè"], ["tiec-hoi-nghi", "Công việc / sự kiện"]];
const services = [["phuc-vu-tai-ban", "Phục vụ tại bàn"], ["buffet", "Buffet"], ["omakase", "Omakase"]];

export function PersonalizedRecommendations() {
  const { user, isAuthenticated } = useAuth(); const { city } = useLocation(); const navigate = useNavigate(); const queryClient = useQueryClient();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState<Preference>({ categories: [], suitable_for: [], service_types: [], price_level: null, city });
  const preference = useQuery<Preference | null>({ queryKey: ["preferences", user?.userId], queryFn: () => api.get("/v1/recommendations/me").then(r => r.data), enabled: isAuthenticated && user?.role === "customer", retry: false });
  const recommended = useQuery<Recommended[]>({ queryKey: ["personalized-recommendations", user?.userId], queryFn: () => api.get("/v1/recommendations/me/restaurants").then(r => r.data), enabled: Boolean(preference.data), retry: false });
  const save = useMutation({ mutationFn: (payload: Preference) => api.put("/v1/recommendations/me", payload), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["preferences", user?.userId] }); void queryClient.invalidateQueries({ queryKey: ["personalized-recommendations", user?.userId] }); setOpen(false); toast.success("Đã lưu khẩu vị của bạn."); }, onError: () => toast.error("Chưa thể lưu khẩu vị. Vui lòng thử lại.") });
  const toggle = (key: "categories" | "suitable_for" | "service_types", value: string) => setForm(current => ({ ...current, [key]: current[key].includes(value) ? current[key].filter(item => item !== value) : [...current[key], value] }));
  const start = () => { if (!isAuthenticated) { toast.error("Vui lòng đăng nhập để nhận đề xuất riêng."); navigate("/login"); return; } if (user?.role !== "customer") { toast.error("Đề xuất khẩu vị dành cho tài khoản khách hàng."); return; } setForm(preference.data ?? { categories: [], suitable_for: [], service_types: [], price_level: null, city }); setOpen(true); };
  return <section className="rounded-2xl border border-red-100 bg-white p-6 shadow-sm">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-bold text-slate-900">TableNow đề xuất cho riêng bạn</h2><p className="mt-1 text-sm text-slate-500">Nhà hàng được chọn dựa trên khẩu vị và nhu cầu của bạn.</p></div><button type="button" onClick={start} className="rounded-xl border border-red-200 px-4 py-2 text-sm font-bold text-red-600 hover:bg-red-50">{preference.data ? "Cập nhật khẩu vị" : "Chọn khẩu vị của bạn"}</button></div>
    {recommended.isLoading && <p className="mt-6 text-sm text-slate-500">Đang tìm nhà hàng phù hợp…</p>}
    {recommended.data?.length ? <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{recommended.data.map(item => <button type="button" key={item.id} onClick={() => navigate(`/restaurant/${item.id}`)} className="overflow-hidden rounded-xl border text-left hover:border-red-300"><img className="h-28 w-full object-cover" src={item.image_url || "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800"} alt={item.name}/><div className="p-3"><p className="truncate font-bold text-slate-900">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.match_reasons.join(" · ")}</p></div></button>)}</div> : preference.data && !recommended.isLoading ? <p className="mt-6 text-sm text-slate-500">Chưa tìm thấy nhà hàng khớp hoàn toàn. Hãy cập nhật khẩu vị để nhận thêm lựa chọn.</p> : <p className="mt-6 text-sm text-slate-500">Hoàn tất khảo sát ngắn để nhận đề xuất riêng.</p>}
    {open && <div className="fixed inset-0 z-60 flex items-center justify-center bg-black/50 p-4"><form onSubmit={event => { event.preventDefault(); save.mutate(form); }} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6"><h3 className="text-xl font-bold">Khẩu vị của bạn</h3><p className="mt-1 text-sm text-slate-500">Chọn các lựa chọn phù hợp nhất; bạn có thể thay đổi bất cứ lúc nào.</p><ChoiceGroup label="Món yêu thích" options={RESTAURANT_CATEGORIES.map(item => [item.slug, item.label])} selected={form.categories} onToggle={value => toggle("categories", value)}/><ChoiceGroup label="Dịp đi ăn" options={occasions} selected={form.suitable_for} onToggle={value => toggle("suitable_for", value)}/><ChoiceGroup label="Kiểu phục vụ" options={services} selected={form.service_types} onToggle={value => toggle("service_types", value)}/><label className="mt-5 block text-sm font-bold">Mức giá mong muốn<select value={form.price_level ?? ""} onChange={event => setForm(current => ({ ...current, price_level: event.target.value ? Number(event.target.value) : null }))} className="mt-2 w-full rounded-xl border p-3"><option value="">Chưa chọn</option>{[1,2,3,4,5].map(level => <option key={level} value={level}>Mức {level}</option>)}</select></label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="rounded-xl px-4 py-2 text-sm font-bold">Hủy</button><button disabled={save.isPending} className="rounded-xl bg-red-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-60">{save.isPending ? "Đang lưu…" : "Lưu và xem đề xuất"}</button></div></form></div>}
  </section>;
}
function ChoiceGroup({ label, options, selected, onToggle }: { label: string; options: string[][]; selected: string[]; onToggle: (value: string) => void }) { return <fieldset className="mt-5"><legend className="text-sm font-bold">{label}</legend><div className="mt-2 flex flex-wrap gap-2">{options.map(([value, text]) => <button type="button" key={value} onClick={() => onToggle(value)} className={`rounded-full border px-3 py-1.5 text-sm ${selected.includes(value) ? "border-red-600 bg-red-50 text-red-700" : "border-slate-200"}`}>{text}</button>)}</div></fieldset>; }
