import { useEffect } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { refundMoney, useBookingRefund, type DepositRefund } from "../services/refund";
import { useTranslation } from "react-i18next";

export function RefundTimeline({ refund }: { refund: DepositRefund }) {
  const { i18n, t } = useTranslation(); const language = i18n.language === "en" ? "en" : "vi"; const stage = refund.status === "refunded" ? 3 : refund.status === "processing" ? 2 : 1;
  const steps = language === "en" ? ["Add payout details", "Refund in progress", "Deposit refunded"] : ["Chờ thông tin nhận tiền", "Đã nhận thông tin, chờ hoàn cọc", "Đã hoàn tiền đặt cọc"];
  return <div className="space-y-3 text-sm" aria-live="polite"><ol className="space-y-2" aria-label={t("refund.timeline")}>{steps.map((label, i) => <li key={label} aria-current={stage === i + 1 ? "step" : undefined} className={stage >= i + 1 ? "font-semibold text-red-700" : "text-gray-400"}>{stage > i + 1 ? "✓" : `${i + 1}.`} {label}</li>)}</ol>{refund.status === "pending" && <p>{language === "en" ? "Please provide your payout details so we can process the refund." : "Vui lòng cung cấp tài khoản để chúng tôi xử lý hoàn tiền."}</p>}{refund.status === "processing" && <p>{language === "en" ? "We’ve received your details and will notify you once the refund is sent." : "Thông tin đã được tiếp nhận. Chúng tôi sẽ thông báo khi đã chuyển tiền."}</p>}{refund.refunded_at && <p>{language === "en" ? "Refunded on:" : "Thời gian hoàn:"} {new Date(refund.refunded_at).toLocaleString(language === "en" ? "en-US" : "vi-VN")}</p>}{refund.status === "refunded" && refund.proof_url && <a className="font-semibold text-red-700 underline" href={refund.proof_url} target="_blank" rel="noreferrer">{language === "en" ? "View refund proof" : "Xem minh chứng hoàn tiền"}</a>}</div>;
}

export function RefundProgress({ bookingId }: { bookingId: number }) {
  const q = useBookingRefund(bookingId); const qc = useQueryClient(); const { i18n, t } = useTranslation(); const language = i18n.language === "en" ? "en" : "vi";
  useEffect(() => { if (q.data?.status === "refunded") { void qc.invalidateQueries({ queryKey: ["booking-detail", String(bookingId)] }); void qc.invalidateQueries({ queryKey: ["my-bookings"] }); } }, [q.data?.status, bookingId, qc]);
  if (q.isLoading) return <p>{t("refund.loading")}</p>; if (q.isError || !q.data) return <button type="button" onClick={() => void q.refetch()} className="text-red-600">{t("refund.loadFailed")}</button>;
  const status = q.data.status === "pending" ? (language === "en" ? "Waiting for payout details" : "Chờ thông tin nhận tiền") : q.data.status === "processing" ? (language === "en" ? "Refund in progress" : "Đang hoàn cọc") : (language === "en" ? "Deposit refunded" : "Đã hoàn tiền đặt cọc");
  const refund = q.data;
  return <section className="space-y-3 rounded-xl border border-red-100 bg-white p-5"><h4 className="font-bold">{status}</h4><RefundTimeline refund={refund} />{refund.status === "pending" && <Link to={`/account/bookings/${bookingId}/refund`} className="inline-block rounded-lg bg-red-600 px-4 py-2 font-semibold text-white transition hover:bg-red-700">{t("refund.addDetails")}</Link>}{refund.status === "refunded" && <><button type="button" onClick={() => window.print()} className="rounded-lg border border-gray-300 px-4 py-2 text-sm font-bold text-gray-700 print:hidden">In hóa đơn hoàn cọc</button><div className="hidden rounded-xl border border-gray-300 p-6 text-gray-900 print:block"><p className="text-xs font-bold tracking-widest">TABLENOW</p><h1 className="mt-2 text-xl font-bold">HÓA ĐƠN HOÀN TIỀN ĐẶT CỌC</h1><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-gray-500">Mã hoàn cọc</dt><dd className="font-semibold">#{refund.id}</dd></div><div><dt className="text-gray-500">Đơn đặt bàn</dt><dd className="font-semibold">#{refund.booking_id}</dd></div><div><dt className="text-gray-500">Thời gian hoàn</dt><dd className="font-semibold">{refund.refunded_at ? new Date(refund.refunded_at).toLocaleString("vi-VN") : "—"}</dd></div><div><dt className="text-gray-500">Số tiền đã hoàn</dt><dd className="text-lg font-bold">{refundMoney(refund.amount)}</dd></div><div><dt className="text-gray-500">Ngân hàng nhận</dt><dd className="font-semibold">{refund.bank_name || "—"}</dd></div><div><dt className="text-gray-500">Tài khoản nhận</dt><dd className="font-semibold">{refund.account_number || "—"}</dd></div></dl><p className="mt-6 border-t pt-4 text-xs text-gray-500">Hóa đơn điện tử được tạo bởi TableNow.</p></div></>}</section>;
}
