ALTER TABLE restaurant ADD COLUMN IF NOT EXISTS description VARCHAR;
ALTER TABLE restaurant ADD COLUMN IF NOT EXISTS "totalSeats" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE restaurant ADD COLUMN IF NOT EXISTS "availableSeats" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE restaurant ADD COLUMN IF NOT EXISTS "managerID" INTEGER;
ALTER TABLE restaurant ADD CONSTRAINT fk_restaurant_manager FOREIGN KEY ("managerID") REFERENCES "user"("userId");
