"""init

Revision ID: 08318fb7c5e3
Revises: 
Create Date: 2026-06-30 10:23:15.395106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # type: ignore
import sqlmodel # type: ignore



# revision identifiers, used by Alembic.
revision: str = '08318fb7c5e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('createdAt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('image_url', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('price_avg', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('has_exclusive', sa.Boolean(), nullable=False),
    sa.Column('category', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('suitable_for', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('service_types', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_restaurants_capacity'), 'restaurants', ['capacity'], unique=False)
    op.create_index(op.f('ix_restaurants_district'), 'restaurants', ['district'], unique=False)
    op.create_index(op.f('ix_restaurants_has_exclusive'), 'restaurants', ['has_exclusive'], unique=False)
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.create_index(op.f('ix_restaurants_like_count'), 'restaurants', ['like_count'], unique=False)
    op.create_index(op.f('ix_restaurants_price_avg'), 'restaurants', ['price_avg'], unique=False)
    op.create_index(op.f('ix_restaurants_rating'), 'restaurants', ['rating'], unique=False)
    op.create_index(op.f('ix_restaurants_review_count'), 'restaurants', ['review_count'], unique=False)
    op.create_table('restaurant_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('image_urls', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('image_menu', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('price_range', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opening_time', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('parking_info', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('utilities', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id')
    )
    op.create_index(op.f('ix_restaurant_details_id'), 'restaurant_details', ['id'], unique=False)
    op.create_table('restaurant_menu_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_menu_lists_id'), 'restaurant_menu_lists', ['id'], unique=False)
    op.create_index(op.f('ix_restaurant_menu_lists_is_available'), 'restaurant_menu_lists', ['is_available'], unique=False)
    op.create_index(op.f('ix_restaurant_menu_lists_price'), 'restaurant_menu_lists', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurant_menu_lists_price'), table_name='restaurant_menu_lists')
    op.drop_index(op.f('ix_restaurant_menu_lists_is_available'), table_name='restaurant_menu_lists')
    op.drop_index(op.f('ix_restaurant_menu_lists_id'), table_name='restaurant_menu_lists')
    op.drop_table('restaurant_menu_lists')
    op.drop_index(op.f('ix_restaurant_details_id'), table_name='restaurant_details')
    op.drop_table('restaurant_details')
    op.drop_index(op.f('ix_restaurants_review_count'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_rating'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_price_avg'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_like_count'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_has_exclusive'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_district'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_capacity'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_table('user')
    # ### end Alembic commands ###
