"""0507

Revision ID: 08ec1ac4211c
Revises: 8eae97e42914
Create Date: 2026-07-05 18:15:07.835944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa #type: ignore
import sqlmodel #type: ignore



# revision identifiers, used by Alembic.
revision: str = '08ec1ac4211c'
down_revision: Union[str, Sequence[str], None] = '8eae97e42914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menuitem')
    op.add_column('restaurant_menu_lists', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('restaurant_menu_lists', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.drop_column('restaurant_menu_lists', 'dish_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_menu_lists', sa.Column('dish_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('restaurant_menu_lists', 'category')
    op.drop_column('restaurant_menu_lists', 'name')
    op.create_table('menuitem',
    sa.Column('itemId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('restaurantId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurants.id'], name=op.f('menuitem_restaurantId_fkey')),
    sa.PrimaryKeyConstraint('itemId', name=op.f('menuitem_pkey'))
    )
    # ### end Alembic commands ###
