"""add_partner_verification_fields

Revision ID: 3a83270de910
Revises: ee7466872964
Create Date: 2026-05-11 03:14:41.911400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a83270de910'
down_revision: Union[str, Sequence[str], None] = 'ee7466872964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('restaurant', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Update existing rows to 'active'
    op.execute("UPDATE restaurant SET status = 'active'")
    
    # Now set to non-nullable
    op.alter_column('restaurant', 'status', nullable=False)
    
    op.add_column('restaurant', sa.Column('businessLicenseUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('restaurant', sa.Column('taxId', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'taxId')
    op.drop_column('restaurant', 'businessLicenseUrl')
    op.drop_column('restaurant', 'status')
    # ### end Alembic commands ###
