"""update restaurant cuisines and images

Revision ID: 3f8bd99c96cd
Revises: a89a38529656
Create Date: 2026-05-01 18:41:14.407725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8bd99c96cd'
down_revision: Union[str, Sequence[str], None] = 'a89a38529656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'imageUrl',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='json_build_array("imageUrl")')
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.drop_constraint(op.f('user_phone_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_phone_key'), 'user', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('restaurant', 'imageUrl',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
