"""0607

Revision ID: 4a1d08c2b10b
Revises: 9d766aa495cc
Create Date: 2026-07-06 18:37:36.449903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '4a1d08c2b10b'
down_revision: Union[str, Sequence[str], None] = '9d766aa495cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'isPaid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('isPaid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
