"""0207

Revision ID: 57ad27edb27f
Revises: 08318fb7c5e3
Create Date: 2026-07-02 18:00:02.588191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa #type: ignore



# revision identifiers, used by Alembic.
revision: str = '57ad27edb27f'
down_revision: Union[str, Sequence[str], None] = '08318fb7c5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
