"""remove_branch_and_update_cuisine_to_list

Revision ID: 8c1dc624ecd3
Revises: a8260d0c0152
Create Date: 2026-05-05 00:05:09.127400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c1dc624ecd3'
down_revision: Union[str, Sequence[str], None] = 'a8260d0c0152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branch')
    op.alter_column('restaurant', 'cuisine',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               postgresql_using="json_build_array(cuisine)",
               existing_nullable=False)
    op.drop_column('restaurant', 'cuisines')
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('restaurant', sa.Column('cuisines', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('restaurant', 'cuisine',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('branch',
    sa.Column('branchId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('restaurantId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('totalSeats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('availableSeats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurant.restaurantId'], name=op.f('branch_restaurantId_fkey')),
    sa.PrimaryKeyConstraint('branchId', name=op.f('branch_pkey'))
    )
    # ### end Alembic commands ###
