"""Drop rating and reviewCount

Revision ID: a8260d0c0152
Revises: 52a56693f5dd
Create Date: 2026-05-04 22:50:07.256475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8260d0c0152'
down_revision: Union[str, Sequence[str], None] = '52a56693f5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'rating')
    op.drop_column('restaurant', 'reviewCount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('reviewCount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('restaurant', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
