"""update booking

Revision ID: a89a38529656
Revises: b674d34a6b3e
Create Date: 2026-03-09 12:57:36.909154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89a38529656'
down_revision: Union[str, Sequence[str], None] = 'b674d34a6b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('bookingId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('restaurantId', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('guestCount', sa.Integer(), nullable=False),
    sa.Column('requestSeats', sa.Integer(), nullable=False),
    sa.Column('assignedSeats', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('contactName', sa.String(), nullable=False),
    sa.Column('contactEmail', sa.String(), nullable=False),
    sa.Column('contactPhone', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('createdAt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurant.restaurantId'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.userId'], ),
    sa.PrimaryKeyConstraint('bookingId')
    )
    op.add_column('restaurant', sa.Column('description', sa.String(), nullable=True))
    # Use temporary server defaults so existing rows can satisfy NOT NULL on add.
    op.add_column('restaurant', sa.Column('totalSeats', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('restaurant', sa.Column('availableSeats', sa.Integer(), nullable=False, server_default='0'))
    # Keep nullable during migration because existing restaurants may not have a manager yet.
    op.add_column('restaurant', sa.Column('managerID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'restaurant', 'user', ['managerID'], ['userId'])
    op.alter_column('restaurant', 'totalSeats', server_default=None)
    op.alter_column('restaurant', 'availableSeats', server_default=None)
    op.add_column('user', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('user', sa.Column('createdAt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'createdAt')
    op.drop_column('user', 'avatar')
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.drop_column('restaurant', 'managerID')
    op.drop_column('restaurant', 'availableSeats')
    op.drop_column('restaurant', 'totalSeats')
    op.drop_column('restaurant', 'description')
    op.drop_table('booking')
    # ### end Alembic commands ###
