"""delete table menu

Revision ID: b674d34a6b3e
Revises: 4f6c1aa37f4e
Create Date: 2026-02-28 20:04:26.338404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b674d34a6b3e'
down_revision: Union[str, Sequence[str], None] = '4f6c1aa37f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('menuitem_menuId_fkey'), 'menuitem', type_='foreignkey')
    op.drop_column('menuitem', 'menuId')
    op.drop_table('menu')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('menuId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('restaurantId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['restaurantId'], ['restaurant.restaurantId'], name=op.f('menu_restaurantId_fkey')),
    sa.PrimaryKeyConstraint('menuId', name=op.f('menu_pkey'))
    )
    op.add_column('menuitem', sa.Column('menuId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('menuitem_menuId_fkey'), 'menuitem', 'menu', ['menuId'], ['menuId'])
    # ### end Alembic commands ###
