"""0507

Revision ID: b9ca31914f52
Revises: 07918542904b
Create Date: 2026-07-05 16:49:53.085141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'b9ca31914f52'
down_revision: Union[str, Sequence[str], None] = '07918542904b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_details', sa.Column('regulations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_details', 'regulations')
    # ### end Alembic commands ###
