"""add_restaurant_denormalized_fields

Revision ID: e6dab2242e08
Revises: 3a83270de910
Create Date: 2026-05-24 22:22:30.850859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6dab2242e08'
down_revision: Union[str, Sequence[str], None] = '3a83270de910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'isPaid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('restaurant', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('restaurant', 'reviewCount',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('restaurant', 'priceRange',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Chưa cập nhật'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant', 'priceRange',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Chưa cập nhật'::character varying"))
    op.alter_column('restaurant', 'reviewCount',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('restaurant', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('booking', 'isPaid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
