"""Remove priceRange from Restaurant

Revision ID: ee7466872964
Revises: 8c1dc624ecd3
Create Date: 2026-05-05 07:35:55.835446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7466872964'
down_revision: Union[str, Sequence[str], None] = '8c1dc624ecd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'priceRange')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('priceRange', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
