export const bookingVi: Record<string, string> = {
  "booking.none": "Chưa có", "booking.loadingDetail": "Đang tải chi tiết đơn đặt bàn...", "booking.notFound": "Không tìm thấy đơn đặt bàn", "booking.notFoundHelp": "Đơn này không tồn tại hoặc bạn không có quyền xem.", "booking.home": "Về trang chủ", "booking.myBookings": "Đơn đặt bàn của tôi", "booking.myBookingsHelp": "Theo dõi các đơn đang chờ, đã xác nhận và đã hoàn thành.", "booking.loading": "Đang tải đơn đặt bàn...", "booking.empty": "Bạn chưa có đơn đặt bàn nào.", "booking.restaurantFallback": "Nhà hàng #{{id}}", "booking.guests": "{{count}} khách", "booking.viewDetails": "Xem chi tiết", "booking.detailKicker": "Chi tiết đơn đặt bàn", "booking.detailTitle": "Thông tin đặt bàn", "booking.bookedFor": "Đặt lúc {{date}} · {{time}}", "booking.viewRestaurant": "Xem nhà hàng", "booking.reportRestaurant": "Báo cáo nhà hàng", "booking.guestsTotal": "Tổng số khách", "booking.children": "Trẻ em đi cùng", "booking.seats": "Số chỗ ngồi", "booking.people": "{{count}} người", "booking.childrenCount": "{{count}} trẻ em", "booking.seatsCount": "{{count}} chỗ", "booking.items": "Món đi kèm", "booking.noItems": "Đơn này chưa chọn món đi kèm.", "booking.note": "Ghi chú", "booking.contact": "Thông tin liên hệ", "booking.fullName": "Họ tên", "booking.phone": "SĐT", "booking.deposit": "Thanh toán đặt cọc", "booking.amount": "Số tiền", "booking.status": "Trạng thái", "booking.processing": "Trạng thái xử lý", "booking.createdAt": "Ngày tạo", "booking.subtotal": "Tạm tính", "booking.itemCount": "Tổng số món", "booking.deposit.paid": "Đã thanh toán", "booking.deposit.refundPending": "Đang xử lý hoàn cọc", "booking.deposit.refunded": "Đã hoàn cọc", "booking.deposit.expired": "Hết hạn đặt cọc", "booking.deposit.awaiting": "Chờ thanh toán",
  "booking.paymentFailed": "Thanh toán không thành công hoặc đã hết hạn. Vui lòng tạo đơn mới nếu vẫn muốn đặt bàn.", "booking.addRefundDetails": "Cung cấp thông tin hoàn cọc", "booking.viewRefund": "Xem kết quả hoàn cọc",
  "booking.status.payment_expired": "Thanh toán hết hạn", "booking.status.pending": "Chờ xác nhận", "booking.status.confirmed": "Đã xác nhận", "booking.status.completed": "Hoàn thành", "booking.status.cancelled": "Đã hủy", "booking.status.awaiting_payment": "Chờ thanh toán", "booking.status.expired": "Đã hết hạn",
};
export const bookingEn: Record<string, string> = {
  "booking.none": "Not available", "booking.loadingDetail": "Loading booking details...", "booking.notFound": "Booking not found", "booking.notFoundHelp": "This booking doesn't exist or you don't have permission to view it.", "booking.home": "Back to home", "booking.myBookings": "My bookings", "booking.myBookingsHelp": "Track your pending, confirmed, and completed bookings.", "booking.loading": "Loading bookings...", "booking.empty": "You don't have any bookings yet.", "booking.restaurantFallback": "Restaurant #{{id}}", "booking.guests": "{{count}} guests", "booking.viewDetails": "View details", "booking.detailKicker": "Booking details", "booking.detailTitle": "Your reservation", "booking.bookedFor": "Booked for {{date}} · {{time}}", "booking.viewRestaurant": "View restaurant", "booking.reportRestaurant": "Report restaurant", "booking.guestsTotal": "Total guests", "booking.children": "Children", "booking.seats": "Seats requested", "booking.people": "{{count}} people", "booking.childrenCount": "{{count}} children", "booking.seatsCount": "{{count}} seats", "booking.items": "Add-ons", "booking.noItems": "No add-ons were selected for this booking.", "booking.note": "Note", "booking.contact": "Contact details", "booking.fullName": "Full name", "booking.phone": "Phone", "booking.deposit": "Deposit payment", "booking.amount": "Amount", "booking.status": "Status", "booking.processing": "Processing status", "booking.createdAt": "Created on", "booking.subtotal": "Subtotal", "booking.itemCount": "Total items", "booking.deposit.paid": "Paid", "booking.deposit.refundPending": "Refund in progress", "booking.deposit.refunded": "Refunded", "booking.deposit.expired": "Deposit expired", "booking.deposit.awaiting": "Awaiting payment",
  "booking.paymentFailed": "Payment was unsuccessful or has expired. Create a new booking if you would still like to reserve a table.", "booking.addRefundDetails": "Provide refund details", "booking.viewRefund": "View refund result",
  "booking.status.payment_expired": "Payment expired", "booking.status.pending": "Pending confirmation", "booking.status.confirmed": "Confirmed", "booking.status.completed": "Completed", "booking.status.cancelled": "Cancelled", "booking.status.awaiting_payment": "Awaiting payment", "booking.status.expired": "Expired",
};
